### ISSUE TITLE
Build fails with TypeError: this.getOptions is not a function

### ISSUE THREAD

**Issue by Fabian-K** [mpetuska/kmdc#176]
Hey,

this looks like a cool project! I want to try it out in a sample project, however, my build currently fails with:

```
Module build failed (from kotlin-compose-web-playground/build/js/node_modules/style-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (kotlin-compose-web-playground/build/js/node_modules/style-loader/dist/index.js:19:24)
```

I also see the following warning during `Task :kotlinNpmInstall``

```
warning "workspace-aggregator-ca44f0e4-4b75-4d19-8a3f-c01987bf9f3e > kotlin-compose-web-playground-test > karma-webpack@5.0.0" has incorrect peer dependency "webpack@^5.0.0".
warning "workspace-aggregator-ca44f0e4-4b75-4d19-8a3f-c01987bf9f3e > kotlin-compose-web-playground-test > css-loader@6.7.1" has incorrect peer dependency "webpack@^5.0.0".
warning "workspace-aggregator-ca44f0e4-4b75-4d19-8a3f-c01987bf9f3e > kotlin-compose-web-playground-test > style-loader@3.3.1" has incorrect peer dependency "webpack@^5.0.0".
warning "workspace-aggregator-ca44f0e4-4b75-4d19-8a3f-c01987bf9f3e > kotlin-compose-web-playground-test > sass-loader@13.0.2" has incorrect peer dependency "webpack@^5.0.0".
warning Ignored scripts due to flag.
```

Do you have any idea what might cause this or any hint where to look at?

Thanks, Fabian

**Comment by mpetuska** [comment]
Hmm, looks like corrupted yarn lockfile. I suggest deleting kotlin-js-store folder and then running "gradle clean build"

**Comment by Fabian-K** [comment]
Thanks for the quick reply! Unfortunately, that did not help. The full build output is available at https://github.com/Fabian-K/repro-kmdc/blob/main/build-log.txt (as well as the entire project)

**Comment by mpetuska** [comment]
Ah, thanks! This helps a ton! I'll clone it tomorrow and let you know what's what.

**Comment by mpetuska** [comment]
Ok, this turned out to be a webpack issue as I've suspected. To get your repro working you need to do the following:
1. Remove [this](https://github.com/Fabian-K/repro-kmdc/blob/main/gradle.properties#L3) property
2. Run `./gradlew kotlinUpgradeYarnLock`
3. Test with `./gradlew jsBrowserRun`

In short, KGP does not apply css/scss configuration properly when forced to webpack 4. It's always best to use whatever webpack version KGP defaults to to avoid such issues moving forward.

**Comment by Fabian-K** [comment]
Perfect, thanks a lot! 

I was using the IntelliJ built-in project scaffolding for a Compose Multiplatform project targeting web. That´s where the property was coming from...
