### ISSUE TITLE
MDCTextField doesn't support `password` input type

### ISSUE THREAD

**Issue by e13mort** [mpetuska/kmdc#215]
As far as I understand `@Composable MDCTextFieldInput(...)` function uses `@Composable TextInput(...)` function from html compose. There are some other input functions (like `@Composable PasswordInput(...)` that might be wrapped with KMDC.

**Comment by mpetuska** [comment]
Hmm, compose-html is just a rendering engine used by kmdc. Mainly the source of truth is material-design-components which this wraps so in this case one should follow mdc recommendations to build a password field. That being said, password field is common enough use-case to be worth providing custom kmdcx components for. I'll look into it when I find the time.

**Comment by e13mort** [comment]
I understand the approach with kmds wrapping the mdc components. But, the corresponding description https://m2.material.io/components/text-fields/web#other-features says that one should use plain html input tag ```  <input class="mdc-text-field__input" type="password" aria-labelledby="my-label-id" required minlength="8"> ``` on order to get desired password behaviour. That's why I came up with a suggestion to provide a way to specify `@Composable` input function inside the kmcd library.
