### ISSUE TITLE
Implement kmdc-icons

### ISSUE THREAD

**Issue by mpetuska** [mpetuska/kmdc#33]
New module should provide DSLs for [material-icons](https://fonts.google.com/icons?selected=Material+Icons) [npm-package](https://github.com/marella/material-icons)

**Comment by pocharlebois** [comment]
@mpetuska I'm working on this one. I'm not sure how contributions works but can you grant me the ability to create a branch and , when I'm ready, a PR?

**Comment by mpetuska** [comment]
Welcome, thanks for contributing. I've been procrastinating writing up proper contribution guidelines, so confusion is natural. Apologies for that.

For now, the usual open source process is that you fork the repo and make the changes on your fork. When ready, you can raise a PR from your fork to this repo.
