### ISSUE TITLE
Generate DOM element IDs with lower collision risk

### ISSUE THREAD

**Issue by OliverO2** [mpetuska/kmdc#65]
There is code generating DOM element IDs, which looks like this:
```kotlin
  val localId = remember { Random.nextInt(9999) }
  val radioId = remember { "mdc-radio__native-control__$localId" }
```

The above approach bears some collision risk. This could be avoided and simplified by using a central ID supply function like this:

```kotlin
private val nextDomElementId = 0
fun uniqueDomElementId() = nextDomElementId++
```

and then use it like this:
```kotlin
  val localId = remember { uniqueDomElementId() }
  val radioId = remember { "mdc-radio__native-control__$localId" }
```

This would be collision-free almost forever (until an overflow occurs).

**Comment by mpetuska** [comment]
Hmm, the problem with this approach is that we'd need to expose ID provider publicly. How about using a timestamp at the time of component initialisation as ID instead?

**Comment by OliverO2** [comment]
`uniqueDomElementId()` could be internal, of course. Seems like even exposing that function would't really hurt in practice. Or am I overlooking something?

We could even change its return value to a properly prefixed string such as `"kmdc-{nextDomElementId++}"` and use it directly as a component-specific prefix is not required.

**Comment by OliverO2** [comment]
Ah I see, due to the module separation `internal` is not an option. Still low potential for any kind of abuse even if `public`, it seems. Timestamps might also work, but I'd favor not having to think about sufficient resolution on fast machines, if possible.

**Comment by mpetuska** [comment]
I've recently introduced `@MDCInternalDsl` annotation that requires opt-in or throws an error when annotated public entities are used outside kmdc repo. It might be enough to have public id factory with this annotation to make it safe-enough for abuse.

**Comment by OliverO2** [comment]
Sounds good. Don't copy that shitty code from above. ;-) I forgot a dollar sign, it seems. Maybe this could work `"kmdc-${nextDomElementId++}"`. :-)

**Comment by mpetuska** [comment]
The above would work assuming that you initialise the factory with `0` value -> returning 0 on first call and incrementing it to 1...

**Comment by OliverO2** [comment]
Yeah, the 0 doesn't matter. But I got that https://github.com/mpetuska/kmdc/issues/65#issuecomment-1003375683 string template wrong:

> We could even change its return value to a properly prefixed string such as `"kmdc-{nextDomElementId++}"` and use it directly, as a component-specific prefix is not required.
