### ISSUE TITLE
Wrap mdc-chips

### ISSUE THREAD

**Issue by mpetuska** [mpetuska/kmdc#8]
Wrap [mdc-chips](https://github.com/material-components/material-components-web/tree/v13.0.0/packages/mdc-chips) js module in new `kmdc-chips` module.

**Comment by pocharlebois** [comment]
@mpetuska I'll take this one.

**Comment by mpetuska** [comment]
Thanks. Note that there is already a module ready for it as I had an initial stab at implementing it months ago and had to put it back in the drawer due to shortage of time. Feel free to either build on top of what I've left or remove it and implement from scratch.

**Comment by mpetuska** [comment]
@pocharlebois please pull in latest master version from the upstream before starting any work. I've juts merged some significant refactoring.

**Comment by mpetuska** [comment]
@pocharlebois are you still planning on implementing this? I've finally found some spare time to get back to this project and could pick this up if you no longer have the capacity to complete it.

**Comment by pocharlebois** [comment]
@mpetuska we ended up using a different UI paradigm for the project I am working so I didn't end up implementing the mdc-chips. You can unassign me from the issue for the time being and I'll let you know if I have availability to further support the development of his library. Thanks a lot for your amazing work!

**Comment by mpetuska** [comment]
Hah, I suspected as much. No worries, thanks for clarifying and all your contributions so far.

**Comment by pocharlebois** [comment]
Just be be clear, we are still using KMDC :) But the specific chip was not immediately required.
